[package]
name = "bunyi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
eframe = { version = "0.28.1", features = [ "default" ] }
env_logger = { version = "0.11.5", default-features = false, features = [ "auto-color", "humantime", ] }
thiserror = "1.0.64"
